package dorks

var Dorks = []string{
	"AWS_ACCESS_KEY_ID",
	"AWS_SECRET_ACCESS_KEY",
	"aws_access_key_id",
	"aws_secret_access_key",
	"filename:.env AWS",
	"filename:.env SECRET_KEY",
	"filename:.env DB_PASSWORD",
	"filename:.env MAIL_PASSWORD",
	"filename:.env SMTP_PASSWORD",
	"filename:.env API_KEY",
	"filename:.env TOKEN",
	"filename:.env PRIVATE_KEY",
	"filename:.env ACCESS_KEY",
	"ghp_",
	"gho_",
	"ghu_",
	"ghr_",
	"filename:.github/workflows token",
	"filename:.github secrets",
	"filename:.netrc password",
	"discord.com/api/webhooks",
	"discordapp.com/api/webhooks",
	"hooks.slack.com/services",
	"outlook.office.com/webhook",
	"teams.microsoft.com/webhook",
	"webhook.site",
	"requestbin.com",
	"hookbin.com",
	"webhookrelay.com",
	"postb.in",
	"filename:.env WEBHOOK_URL",
	"filename:.env DISCORD_WEBHOOK",
	"filename:.env SLACK_WEBHOOK_URL",
	"filename:.env TEAMS_WEBHOOK_URL",
	"filename:.env JWT_SECRET",
	"filename:.env JWT_KEY",
	"filename:config.json api_key",
	"filename:settings.py SECRET_KEY",
	"filename:application.yml token",
	"filename:settings.yaml token",
	"filename:id_rsa",
	"filename:id_dsa",
	"filename:identity",
	"filename:authorized_keys",
	"filename:.ssh/config",
	"filename:.ssh/known_hosts",
	"filename:firebase.json",
	"filename:.firebaserc",
	"filename:.env FIREBASE",
	"filename:.env STRIPE_SECRET_KEY",
	"filename:.env STRIPE_PUBLISHABLE_KEY",
	"filename:stripe.js",
	"filename:firebase.js",
	"filename:.npmrc _auth",
	"filename:package.json token",
	"filename:pypirc password",
	"filename:gem credentials",
	"DATABASE_URL",
	"filename:.env DB_",
	"filename:database.yml",
	"filename:db.js",
	"filename:db.json",
	"filename:config.json db_password",
	"filename:.dockercfg",
	"filename:config.json auth",
	"filename:docker-compose.yml password",
	"filename:.docker/config.json",
	"extension:log password",
	"extension:log token",
	"extension:log secret",
	"filename:config.js password",
	"filename:config.json password",
	"filename:settings.ini",
	"filename:application.properties",
	"filename:.bash_history password",
	"filename:.zsh_history token",
	"extension:json password",
	"extension:env password",
	"extension:yaml password",
	"extension:txt secret",
	"extension:ini password",
	"extension:xml token",
}
