package dorks

var Dorks = []string{
	"AWS_ACCESS_KEY_ID",
	"AWS_SECRET_ACCESS_KEY",
	"aws_access_key_id",
	"aws_secret_access_key",
	"filename:.env AWS",
	"filename:.env SECRET_KEY",
	"filename:.env DB_PASSWORD",
	"filename:.env MAIL_PASSWORD",
	"filename:.env SMTP_PASSWORD",
	"filename:.env API_KEY",
	"filename:.env TOKEN",
	"filename:.env PRIVATE_KEY",
	"filename:.env ACCESS_KEY",
	"ghp_",
	"gho_",
	"ghu_",
	"ghr_",
	"filename:.github/workflows token",
	"filename:.github secrets",
	"filename:.netrc password",
	"discord.com/api/webhooks",
	"discordapp.com/api/webhooks",
	"hooks.slack.com/services",
	"outlook.office.com/webhook",
	"teams.microsoft.com/webhook",
	"webhook.site",
	"requestbin.com",
	"hookbin.com",
	"webhookrelay.com",
	"postb.in",
	"filename:.env WEBHOOK_URL",
	"filename:.env DISCORD_WEBHOOK",
	"filename:.env SLACK_WEBHOOK_URL",
	"filename:.env TEAMS_WEBHOOK_URL",
	"filename:.env JWT_SECRET",
	"filename:.env JWT_KEY",
	"filename:config.json api_key",
	"filename:settings.py SECRET_KEY",
	"filename:application.yml token",
	"filename:settings.yaml token",
	"filename:id_rsa",
	"filename:id_dsa",
	"filename:identity",
	"filename:authorized_keys",
	"filename:.ssh/config",
	"filename:.ssh/known_hosts",
	"filename:firebase.json",
	"filename:.firebaserc",
	"filename:.env FIREBASE",
	"filename:.env STRIPE_SECRET_KEY",
	"filename:.env STRIPE_PUBLISHABLE_KEY",
	"filename:stripe.js",
	"filename:firebase.js",
	"filename:.npmrc _auth",
	"filename:package.json token",
	"filename:pypirc password",
	"filename:gem credentials",
	"DATABASE_URL",
	"filename:.env DB_",
	"filename:database.yml",
	"filename:db.js",
	"filename:db.json",
	"filename:config.json db_password",
	"filename:.dockercfg",
	"filename:config.json auth",
	"filename:docker-compose.yml password",
	"filename:.docker/config.json",
	"extension:log password",
	"extension:log token",
	"extension:log secret",
	"filename:config.js password",
	"filename:config.json password",
	"filename:settings.ini",
	"filename:application.properties",
	"filename:.bash_history password",
	"filename:.zsh_history token",
	"extension:json password",
	"extension:env password",
	"extension:yaml password",
	"extension:txt secret",
	"extension:ini password",
	"extension:xml token",
	"password",
	"passwd",
	"pswd",
	"pwd",
	"pass",
	"filename:.env password",
	"filename:.env passwd",
	"filename:.env pswd",
	"filename:.env pwd",
	"filename:.env pass",
	"extension:json passwd",
	"extension:env passwd",
	"extension:yaml passwd",
	"extension:txt passwd",
	"extension:ini passwd",
	"extension:xml passwd",
	"extension:log passwd",
	"filename:.env SENDGRID_API_KEY",
	"filename:.env MAILGUN_API_KEY",
	"filename:.env TWILIO_AUTH_TOKEN",
	"filename:.env TWILIO_ACCOUNT_SID",
	"filename:.env ALGOLIA_API_KEY",
	"filename:.env MAPBOX_TOKEN",
	"filename:.env CLOUDINARY_URL",
	"filename:.env AWS_SESSION_TOKEN",
	"filename:.env GCP_CREDENTIALS",
	"filename:.env AZURE_CLIENT_SECRET",
	"filename:.env OKTA_API_TOKEN",
	"filename:.travis.yml",
	"filename:bitbucket-pipelines.yml",
	"filename:.gitlab-ci.yml",
	"filename:circle.yml",
	"filename:jenkins.yml",
	"filename:buildspec.yml",
	"filename:teamcity.properties",
	"filename:aws-exports.js",
	"filename:awsconfig.js",
	"filename:.aws/credentials",
	"filename:azure-pipelines.yml",
	"filename:firebase-adminsdk.json",
	"filename:google-services.json",
	"filename:client_secret.json",
	"filename:secrets.yml",
	"filename:secrets.yaml",
	"filename:credentials.json",
	"filename:.pypirc",
	"filename:.npmrc",
	"filename:.yarnrc.yml",
	"filename:.terraformrc",
	"filename:debug.log",
	"filename:error.log",
	"extension:log AWS",
	"extension:log secret",
	"extension:txt key",
	"filename:.env SECRET",
	"filename:.env ENCRYPTION_KEY",
	"filename:.env SIGNING_KEY",
	"filename:.env ENCRYPT_KEY",
	"filename:.env PRIVATE_KEY_PEM",
	"extension:pem PRIVATE KEY",
	"extension:key PRIVATE KEY",
	"extension:cer BEGIN CERTIFICATE",
	"extension:crt BEGIN CERTIFICATE",
	"filename:.env PAYPAL_CLIENT_SECRET",
	"filename:.env BRAINTREE_PRIVATE_KEY",
	"filename:.env SQUARE_ACCESS_TOKEN",
	"filename:config.json stripe_secret_key",
	"filename:config.json braintree_key",
	"filename:.env PAYMENT_SECRET",
	"filename:credentials.gcp.json",
	"filename:service-account.json",
	"filename:azureauth.json",
	"filename:azure_credentials.json",
	"filename:config.gcloud",
	"filename:.env AZURE_TENANT_ID",
	"filename:.github/workflows GITHUB_TOKEN",
	"filename:.bitbucket-pipelines.yml password",
	"filename:.circleci/config.yml AWS_SECRET_ACCESS_KEY",
	"filename:.circleci/config.yml DOCKER_PASSWORD",
	"filename:.drone.yml",
	"filename:.env SUPER_SECRET",
	"filename:.env MASTER_KEY",
	"filename:.env ROOT_PASSWORD",
	"filename:.env ADMIN_PASSWORD",
	"filename:env.js SECRET",
	"filename:secrets.js",
	"filename:local.settings.json",
	"filename:secrets.py",
	"filename:secret_config.rb",
	"filename:.env TEST_SECRET",
	"filename:.env DEV_SECRET",
	"filename:.env STAGING_SECRET",
	"filename:.env LOCAL_SECRET",
	"username=admin password=",
	"filename:config.php db_user",
	"filename:.env USERNAME",
	"filename:.env USER",
	"filename:.env ADMIN_USER",
	"filename:.env ADMIN_EMAIL",
	"filename:.env ADMIN_PASS",
	"filename:.env .bak",
	"filename:.env~",
	"extension:swp SECRET",
	"extension:orig SECRET",
	"filename:dump.rdb",
	"filename:backup.sql",
	"filename:db.dump",
	"filename:database.db",
	"filename:.sqlite",
	"filename:setup.cfg password",
	"filename:pip.conf password",
	"filename:tox.ini token",
	"filename:.env SUPABASE_KEY",
	"filename:.env SUPABASE_URL",
	"filename:.env POCKETBASE_KEY",
	"filename:.env N8N_BASIC_AUTH",
	"filename:.env OPENAI_API_KEY",
	"filename:.env GEMINI_API_KEY",
	"filename:.env HUGGINGFACE_API_KEY",
	"filename:.env VERCEL_API_KEY",
	"filename:.env RAILWAY_API_KEY",
	"filename:.env CLOUDFLARE_API_TOKEN",
	"filename:.env CLOUDFLARE_API_KEY",
	"filename:.env PLANETSCALE_PASSWORD",
	"filename:.env PLANETSCALE_USERNAME",
	"extension:tar.gz password",
	"extension:tgz AWS_SECRET_ACCESS_KEY",
	"extension:bak SECRET_KEY",
	"extension:zip AWS_SECRET_ACCESS_KEY",
	"extension:7z password",
	"extension:rar token",
	"filename:backup.tar",
	"filename:dump.sql.gz",
	"filename:db_backup.sql",
	"filename:wordpress.sql",
	"filename:magento.sql",
	"filename:.env MONGO_URI",
	"filename:.env MONGODB_URI",
	"filename:.env POSTGRES_PASSWORD",
	"filename:.env MYSQL_ROOT_PASSWORD",
	"filename:config.json mongodb",
	"filename:settings.py DATABASES",
	"filename:local.py SECRET_KEY",
	"filename:wp-config.php",
	"filename:config.inc.php",
	"filename:config.ini password",
	"filename:phpunit.xml",
	"filename:app.config",
	"filename:.env ZAPIER_WEBHOOK_URL",
	"filename:.env INTEGRATION_WEBHOOK",
	"filename:.env NOTION_TOKEN",
	"filename:.env AIRTABLE_API_KEY",
	"filename:.env LINE_CHANNEL_SECRET",
	"filename:.env LINE_CHANNEL_ACCESS_TOKEN",
	"filename:.env TELEGRAM_BOT_TOKEN",
	"filename:.env DEV_API_KEY",
	"filename:.env STAGING_API_KEY",
	"filename:.env TEST_DB_PASSWORD",
	"filename:.env DEBUG",
	"filename:test_config.json",
	"filename:mock_data.json password",
	"filename:terraform.tfvars AWS_SECRET_ACCESS_KEY",
	"filename:kubeconfig",
	"filename:.kube/config",
	"filename:config.yml aws_access_key_id",
	"filename:credentials aws_secret_access_key",
	"filename:pipeline.yaml password",
	"filename:helm-values.yaml",
	"filename:.env LARAVEL_APP_KEY",
	"filename:.env NEXTAUTH_SECRET",
	"filename:.env NUXT_SECRET",
	"filename:.env DJANGO_SECRET_KEY",
	"filename:.env FLASK_SECRET_KEY",
	"filename:.env RAILS_MASTER_KEY",
	"filename:.env SYMFONY_SECRET",
	"filename:.env TYPO3_ENCRYPTION_KEY",
	"filename:local.settings.php",
	"filename:parameters.yml",
	"filename:.env DIGITALOCEAN_ACCESS_TOKEN",
	"filename:.env DO_API_KEY",
	"filename:.env HEROKU_API_KEY",
	"filename:.env HEROKU_OAUTH_TOKEN",
	"filename:.env RENDER_API_KEY",
	"filename:.env NETLIFY_AUTH_TOKEN",
	"filename:.env GITHUB_APP_PRIVATE_KEY",
	"filename:.env BITBUCKET_CLIENT_SECRET",
	"filename:.env CI_JOB_TOKEN",
	"filename:.env DRONE_TOKEN",
	"filename:cloudbuild.yaml",
	"filename:cloudbuild.yml",
	"filename:.env STRIPE_TEST_SECRET_KEY",
	"filename:.env PAYPAL_SANDBOX_CLIENT_ID",
	"filename:.env PAYPAL_SANDBOX_SECRET",
	"filename:.env BRAINTREE_PUBLIC_KEY",
	"filename:.env BRAINTREE_MERCHANT_ID",
	"filename:.env RAZORPAY_KEY_SECRET",
	"filename:.env RAZORPAY_KEY_ID",
	"filename:.env PAYSTACK_SECRET_KEY",
	"filename:.m2/settings.xml password",
	"filename:.gradle/gradle.properties",
	"filename:.npm-token",
	"filename:.yarnrc",
	"filename:composer.json token",
	"filename:package-lock.json auth",
	"filename:Cargo.toml token",
	"filename:.env ORACLE_PASSWORD",
	"filename:.env DB_URI",
	"filename:.env DATABASE_URI",
	"filename:.env CASSANDRA_PASSWORD",
	"filename:.env REDIS_PASSWORD",
	"filename:.env ELASTIC_PASSWORD",
	"filename:neo4j.conf",
	"filename:orientdb-server-config.xml",
}
